## PUT request to example server
PUT http://localhost:4000/api/v1/patients/6
Content-Type: application/json

{
  "name": "Johnes",
  "lastName": "Does",
  "phoneNumber": "555-12345",
  "address": "CL 20 23 # 23",
  "email": "pedrosanchez@email.com",
  "birthDate": "2000-01-01"
}

###

